# https://travis-ci.org/#!/translate/pootle
sudo: false
language: python
env:
  - TOXENV=py27-django18-sqlite PYTHONPATH=/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages  TOX_TESTENV_PASSENV="PYTHONPATH"
  - TOXENV=py27-django18-mysql PYTHONPATH=/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages  TOX_TESTENV_PASSENV="PYTHONPATH"
  - TOXENV=py27-django18-postgres PYTHONPATH=/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages  TOX_TESTENV_PASSENV="PYTHONPATH"
  # Meta
  - TOXENV=project PYTHONPATH=/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages  TOX_TESTENV_PASSENV="PYTHONPATH"
matrix:
  allow_failures:
    - env: TOXENV=isort
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache:
  directories:
    - pootle/static/js/node_modules
    - pootle/assets
    - $HOME/.cache/pip
before_install:
  # Error as early as possible if we can't compile
  - python -m compileall -q -f -x ".*[.]tox.*" .
install:
  - pip install --upgrade "pip>=8.0" # FIXME remove once Travis support pip8 by default
  - pip install --upgrade "tox>=2.3"
  - pip install
      -r requirements/base.txt
      -r requirements/tests.txt
      -e .

script:
  - tox --sitepackages -e $TOXENV
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    on_failure: always
    on_success: change
    channels:
      - "chat.freenode.net#pootle-dev"
    use_notice: true
    skip_join: true
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a6e983c90a9617548a6d
    on_success: change
    on_failure: always
    on_start: never
services:
  - redis-server
  - elasticsearch
