# https://travis-ci.org/#!/translate/pootle
sudo: false
language: python
env:
  - TOXENV=py27-django18-sqlite
  - TOXENV=py27-django18-mysql
  - TOXENV=py27-django18-postgres
  # Meta
  - TOXENV=sdist
  - TOXENV=eslint
  - TOXENV=docs
  - TOXENV=mo
  - TOXENV=isort
  - TOXENV=pep8_flake8
  - TOXENV=pep257
matrix:
  allow_failures:
    - env: TOXENV=isort
before_cache:
  - rm -f .tox/*/lib/python*/site-packages/.coverage
  - rm -f .tox/*/log/*.log
  - rm -f .tox/log/tox*.log
  - rm -f .tox/docs/log/docs*.log
  - rm -f .tox/eslint/log/eslint*.log
  - rm -f .tox/isort/log/isort*.log
  - rm -f .tox/dist/Pootle*.zip
  - rm -f $HOME/.cache/pip/log/debug.log
  - pyclean .
cache:
  directories:
    - pootle/static/js/node_modules
    - pootle/assets
    - $HOME/.cache/pip
    - docs/_build
    - .tox
before_install:
  # Error as early as possible if we can't compile
  - python -m compileall -q -f -x ".*[.]tox.*" .
install:
  - pip install --upgrade "pip>=8.0" # FIXME remove once Travis support pip8 by default
  - pip install --upgrade "tox>=2.3"
script:
  - tox -e $TOXENV
notifications:
  email:
    on_failure: always
    on_success: change
  irc:
    on_failure: always
    on_success: change
    channels:
      - "chat.freenode.net#pootle-dev"
    use_notice: true
    skip_join: true
    template:
      - "(%{branch} @ %{commit} : %{author}): %{message} %{build_url}"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a6e983c90a9617548a6d
    on_success: change
    on_failure: always
    on_start: never
services:
  - redis-server
  - elasticsearch
